[meta]
name = "Midnight Syntax"
type = "dark"

[syntax]
comment = "#6C7086"
comment_style = "italic"
string = "#A6E3A1"
number = "#FAB387"
boolean = "#FAB387"
null = "#FAB387"
keyword = "#CBA6F7"
keyword_style = "bold"
storage = "#CBA6F7"
operator = "#89DCEB"
function_def = "#89B4FA"
function_def_style = "bold"
function_call = "#89B4FA"
class_name = "#F9E2AF"
class_name_style = "bold"
interface = "#F9E2AF"
interface_style = "italic"
variable = "#CDD6F4"
variable_property = "#89DCEB"
variable_const = "#FAB387"
parameter = "#EBA0AC"
parameter_style = "italic"
type = "#F9E2AF"
namespace = "#F9E2AF"
tag = "#89B4FA"
attribute = "#F9E2AF"
attribute_value = "#A6E3A1"
css_property = "#89DCEB"
css_value = "#FAB387"
css_selector = "#CBA6F7"
css_unit = "#FAB387"
regex = "#F5C2E7"
escape = "#F2CDCD"
punctuation = "#9399B2"
deprecated = "#6C7086"
deprecated_style = "strikethrough"

# PHP
php_variable = "#F38BA8"
php_this = "#F38BA8"
php_this_style = "italic"

# Blade
blade_directive = "#CBA6F7"
blade_directive_style = "bold"
blade_echo = "#F9E2AF"

# Vue
vue_directive = "#CBA6F7"
vue_component = "#89B4FA"
